language: node_js
node_js:
  - "10.15.2"
script:
  - echo "Deploying"

before_script:
  - npm install -g firebase-tools
  - npm install -g @vue/cli@latest
  - npm install

script:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then npm run build; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build; fi

after_success:
  on:
    branch: master
     - firebase deploy --token 1/5P-F8pNcatZYbhCIe60rYzG7kUEyfWXpXhP-MPE1tgfIhveIGxoGPu_bzRhCzVs2
  on:
  branch: develop
    

